#pragma config(Sensor, S1,     radar,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



/*The first part of the program is responsible for rotating the head with the sensor on it back and forth and for preparing the
progress bar on the NXT's display.  This happens over and over again inside of a while loop
*/
void moveRadar()
{

	nMotorEncoder[motorA]=0;
	nMotorEncoderTarget[motorA] = 500;
	motor[motorA]=15;

/*Since the gears on the radar require the motor to turn 5 turns for every full turn of the
head, we turn the motor by 1000 degrees, which results in a head rotation of 1000 / 5 = 200 degrees.
*/

	while (nMotorRunState[motorA] !=runStateIdle)
	{
		//nxtDisplayTextLine(0, nMotorEncoder[motorA]);
		nxtDrawLine(0, 0, 99, 0);  // display a line between the points (0,0) and (99,0)
		nxtDrawLine(0, 4, 99, 4);  // display a line between the points (0,4) and (99,4)

	}

	nMotorEncoder[motorA]=0;
	nMotorEncoderTarget [motorA]= -500;
	motor[motorA]=-15;

	while (nMotorRunState[motorA] !=runStateIdle)
	{
		nxtDrawLine(0, 0, 99, 0);  // display a line between the points (0,0) and (99,0)
		nxtDrawLine(0, 4, 99, 4);  // display a line between the points (0,4) and (99,4)

	}
/*	nMotorEncoder[motorA]=0;

	while (nMotorEncoder[motorA]>-100) // Moving Counter Clockwise
	{
		nxtDrawLine(0, 0, 99, 0);  // display a line between the points (0,0) and (99,0)
		nxtDrawLine(0, 4, 99, 4);  // display a line between the points (0,4) and (99,4)
		motor[motorA]=-25;
	}

	wait10Msec(10); 							// Just in case*/
}
task main()
{
	bFloatDuringInactiveMotorPWM = false;
	while (true)
	{
		moveRadar();
	}


}

// Anadiendo un comentario para git
