#pragma config(Sensor, S4,     radar,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*The first part of the program is responsible for rotating the head with the sensor on it back and forth and for preparing the
progress bar on the NXT's display.  This happens over and over again inside of a while loop
*/

void moveRadar()
{

	nMotorEncoder[motorA]=0;
	nMotorEncoderTarget[motorA] = 1000;
	motor[motorA]=15;

/*Since the gears on the radar require the motor to turn 5 turns for every full turn of the
head, we turn the motor by 1000 degrees, which results in a head rotation of 1000 / 5 = 200 degrees.
*/

	while (nMotorEncoder[motorA] < 1000) //While the motor has not reached its target
		{

			int distance =SensorValue [radar];
			int pos = nMotorEncoder[motorA];
			nxtDrawLine(0, 0, 99, 0);  // display a line between the points (0,0) and (99,0)
			nxtDrawLine(0, 4, 99, 4);  // display a line between the points (0,4) and (99,4)
			//nxtDisplayTextLine(2,"MotorPos: %d", pos);
			//nxtDisplayTextLine(4,"Sonar: %d", distance);
			nxtDrawRect (0, 3, pos/10, 0);  // display how the radar is moving
			nxtDrawCircle (pos/10, distance, 3);
			if (distance < 100 && distance > 4)
			{
				nxtDrawCircle (pos, (distance/100)*64, 3);
			}

		}


	nxtEraseRect (0, 3, 100, 0); 				//Initialize the display

	nMotorEncoder[motorA]=0;
	nMotorEncoderTarget [motorA]= -1000;
	motor[motorA]=-15;

	while (nMotorEncoder[motorA] > -1000)	//While the motor has not reached its target
		{
			int distance =SensorValue [radar];
			int pos = nMotorEncoder[motorA];
			nxtDrawLine(0, 0, 99, 0);  // display a line between the points (0,0) and (99,0)
			nxtDrawLine(0, 4, 99, 4);  // display a line between the points (0,4) and (99,4)
			nxtDisplayTextLine(2,"MotorPos: %d", pos);
			nxtDisplayTextLine(4,"Sonar: %d", distance);
			nxtDrawRect (100, 3, (100 + pos/10), 0);  // display a line between the points (0,4) and (99,4)
		}

	nxtEraseRect (0, 3, 100, 0); 				//Initialize the display
}
/*The second part of the program is responsible for reading the angle position of the sensor head
and filling in the progress bar on the NXT display at that angle position.  The process
repeats rapidly enough to get a reading for every different horizontal postiion on the NXT display.*/


void progressBar()
{
	int pos = nMotorEncoder[motorA];
	nxtDisplayTextLine(2,"MotorPos: %d", pos);
}


task main()
{
//	bFloatDuringInactiveMotorPWM = true;
	while (true)
	{
		moveRadar();
		progressBar();
	}

}

// Anadiendo un comentario para git
